version: 0.2.{build}

image:
  - Visual Studio 2019
  - Ubuntu2004

configuration:
  - Release

platform:
  - x64  

install:
  - sh: sudo apt update
  - sh: sudo apt install -y uuid-dev

init:
  - cmd: cmake --version
  - cmd: msbuild /version

before_build:
  - echo Running cmake...

build_script:
  - cmd: mkdir build32
  - cmd: cd build32
  - cmd: cmake .. -A Win32 -DMySuffix2=32
  - cmd: cmake --build . --config Release
  - cmd: cd ..
  - cmd: mkdir build64
  - cmd: cd build64
  - cmd: cmake .. -A x64 -DMySuffix2=64
  - cmd: cmake --build . --config Release
  - cmd: cd ..
  - cmd: copy bin\Release\libNativeAddInWin??.dll .

  - sh: mkdir build32
  - sh: cd build32
  - sh: cmake -D CMAKE_BUILD_TYPE:STRING=Release -D TARGET_PLATFORM_32:BOOL=ON --build ..
  - sh: cmake --build .
  - sh: cd ..
  - sh: mkdir build64
  - sh: cd build64
  - sh: cmake -D CMAKE_BUILD_TYPE:STRING=Release -D TARGET_PLATFORM_32:BOOL=OFF --build ..
  - sh: cmake --build .
  - sh: cd ..
  - sh: cp bin/libNativeAddInLin??.so .

after_build:
  - cmd: 7z a NativeAddIn.zip libNativeAddInWin??.dll
  - sh: 7z a NativeAddIn.zip libNativeAddInLin??.so

artifacts:
  - path: NativeAddIn.zip
    name: NativeAddIn
