version: 0.3.1.{build}

image:
  - Visual Studio 2019
  - Ubuntu2004

configuration:
  - Release

platform:
  - x64  

install:
  - sh: sudo apt update
  - sh: sudo apt install -y uuid-dev

init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - cmd: 

before_build:
  - cmd: echo %APPVEYOR_BUILD_VERSION% > "version.txt"
  - sh: echo ${APPVEYOR_BUILD_VERSION} > "version.txt"
  - sh: echo "#define VERSION_FULL " ${APPVEYOR_BUILD_VERSION} > "version.h"

build_script:
  - cmd: Powershell.exe -File manifest.ps1 -Project NativeAddIn -Version %APPVEYOR_BUILD_VERSION%

  - cmd: mkdir build32
  - cmd: cd build32
  - cmd: cmake .. -A Win32 -DMySuffix2=32
  - cmd: cmake --build . --config Release
  - cmd: cd ..
  - cmd: mkdir build64
  - cmd: cd build64
  - cmd: cmake .. -A x64 -DMySuffix2=64
  - cmd: cmake --build . --config Release
  - cmd: cd ..
  - cmd: copy bin\Release\libNativeAddInWin??.dll .

  - sh: mkdir build32
  - sh: cd build32
  - sh: cmake -D CMAKE_BUILD_TYPE:STRING=Release -D TARGET_PLATFORM_32:BOOL=ON --build ..
  - sh: cmake --build .
  - sh: cd ..
  - sh: mkdir build64
  - sh: cd build64
  - sh: cmake -D CMAKE_BUILD_TYPE:STRING=Release -D TARGET_PLATFORM_32:BOOL=OFF --build ..
  - sh: cmake --build .
  - sh: cd ..
  - sh: cp bin/libNativeAddInLin??.so .

after_build:
  - cmd: 7z a NativeAddIn.zip libNativeAddInWin??.dll manifest.xml version.txt version.h
  - sh: 7z a NativeAddIn.zip libNativeAddInLin??.so version.txt version.h

artifacts:
  - path: NativeAddIn.zip
    name: NativeAddIn
